# Generated by Django 4.2.3 on 2023-08-18 04:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('productrest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField(default=1)),
                ('order_price', models.FloatField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productrest.product')),
            ],
        ),
    ]
